import { 
  Brain, 
  Globe, 
  Globe2,
  Smartphone, 
  Cloud, 
  Database, 
  Cpu, 
  Shield, 
  ShieldCheck,
  Blocks, 
  Building, 
  Users, 
  Briefcase, 
  FileText, 
  FolderOpen, 
  Mail, 
  MessageCircle, 
  Linkedin, 
  BarChart3, 
  Megaphone, 
  Wallet, 
  ShoppingCart, 
  LucideIcon,
  Sparkles,
  Zap,
  Code,
  Code2,
  Layout,
  Settings,
  Wrench,
  Rocket,
  Target,
  TrendingUp,
  CheckCircle,
  Star,
  Award,
  BookOpen,
  GraduationCap,
  PenTool,
  FileEdit,
  Presentation,
  Video,
  Image,
  Music,
  Palette,
  Figma,
  Chrome,
  Terminal,
  Server,
  ServerCog,
  HardDrive,
  Wifi,
  Monitor,
  Tv,
  Camera,
  Mic,
  Headphones,
  Gamepad2,
  Dribbble,
  Twitter,
  Facebook,
  Instagram,
  Youtube,
  Github,
  Gitlab,
  Slack,
  MessageSquare,
  Phone,
  MailOpen,
  Send,
  Calendar,
  Clock,
  MapPin,
  Navigation,
  Car,
  Train,
  Plane,
  Home,
  Building2,
  Store,
  CreditCard,
  Banknote,
  PiggyBank,
  Receipt,
  Calculator,
  ChartLine,
  PieChart,
  Gauge,
  Activity,
  Heart,
  Stethoscope,
  Pill,
  Syringe,
  Baby,
  User,
  UserCircle,
  Users2,
  UserPlus,
  Crown,
  Gem,
  Medal,
  Trophy,
  Flag,
  Flame,
  Sun,
  Moon,
  CloudSun,
  CloudRain,
  Snowflake,
  Wind,
  Droplet,
  Leaf,
  TreePine,
  Flower,
  Bug,
  Fish,
  Bird,
  PawPrint,
  Cat,
  Dog,
  Coffee,
  Pizza,
  Utensils,
  Wine,
  Beer,
  Cookie,
  IceCream,
  Candy,
  Gift,
  PartyPopper,
  Ribbon,
  Scissors,
  Ruler,
  Eraser,
  Pencil,
  Highlighter,
  Paintbrush,
  SprayCan,
  Layers,
  Grid,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Pentagon,
  Octagon,
  Diamond,
  Cross,
  Plus,
  Minus,
  Divide,
  Equal,
  Hash,
  Percent,
  DollarSign,
  Euro,
  PoundSterling,
  Bitcoin,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  ArrowUpLeft,
  ArrowDownLeft,
  ChevronsUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  CornerUpLeft,
  CornerUpRight,
  CornerDownLeft,
  CornerDownRight,
  Move,
  Maximize,
  Minimize,
  Expand,
  Shrink,
  Fullscreen,
  Minimize2,
  Maximize2,
  ExternalLink,
  Link,
  Unlink,
  Copy,
  Clipboard,
  Undo,
  Redo,
  RefreshCw,
  RefreshCcwDot,
  RotateCw,
  RotateCcw,
  FlipHorizontal,
  FlipVertical,
  ZoomIn,
  ZoomOut,
  Search,
  Filter,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  List,
  ListOrdered,
  ListTodo,
  CheckSquare,
  CircleDot,
  Radio,
  ToggleLeft,
  ToggleRight,
  Sliders,
  Volume2,
  VolumeX,
  Bell,
  BellRing,
  BellOff,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  ShieldAlert,
  ShieldX,
  Key,
  Fingerprint,
  IdCard,
  Package,
  Truck,
  Box,
  Play,
  Film,
  Puzzle,
  Kanban,
  Map,
  IndianRupee,
  Bot,
  BrainCircuit,
  Workflow,
} from 'lucide-react';

type IconMap = Record<string, LucideIcon>;

const iconMapping: IconMap = {
  // AI & Technology
  'ai': BrainCircuit,
  'artificial intelligence': BrainCircuit,
  'machine learning': BrainCircuit,
  'ml': BrainCircuit,
  'neural': BrainCircuit,
  'deep learning': BrainCircuit,
  'nlp': BrainCircuit,
  'natural language': BrainCircuit,
  'computer vision': Eye,
  'predictive': TrendingUp,
  'automate': Zap,
  'workflow': Workflow,
  'rpa': Zap,
  'ai agent': Bot,
  'chatbot': MessageCircle,
  'bot': Bot,
  'robot': Bot,
  
  // Web & Internet
  'website': Globe2,
  'web': Globe2,
  'internet': Globe2,
  'online': Globe2,
  'digital': Globe2,
  'domain': Globe2,
  'hosting': Server,
  'server': Server,
  'cloud': Cloud,
  'saas': Cloud,
  'paas': Cloud,
  'iaas': Cloud,
  'aws': Cloud,
  'azure': Cloud,
  'gcp': Cloud,
  'infrastructure': ServerCog,
  'devops': ServerCog,
  
  // Mobile & Apps
  'mobile': Smartphone,
  'app': Smartphone,
  'application': Smartphone,
  'ios': Smartphone,
  'android': Smartphone,
  'react native': Smartphone,
  'flutter': Smartphone,
  'native': Smartphone,
  'cross-platform': Smartphone,
  'pwa': Smartphone,
  
  // Database & Data
  'database': Database,
  'data': Database,
  'storage': Database,
  'sql': Database,
  'nosql': Database,
  'mongodb': Database,
  'postgresql': Database,
  'mysql': Database,
  'analytics': BarChart3,
  'analysis': BarChart3,
  'bi': BarChart3,
  'business intelligence': BarChart3,
  'dashboard': BarChart3,
  'visualization': BarChart3,
  'chart': BarChart3,
  'report': BarChart3,
  'etl': Database,
  'pipeline': Database,
  'warehouse': Database,
  
  // Security
  'security': ShieldCheck,
  'cyber security': ShieldCheck,
  'cybersecurity': ShieldCheck,
  'privacy': ShieldCheck,
  'protection': ShieldCheck,
  'firewall': ShieldCheck,
  'encryption': Lock,
  'auth': Key,
  'authentication': Key,
  'authorization': Key,
  'access': Key,
  
  // Blockchain & Crypto
  'blockchain': Blocks,
  'crypto': Bitcoin,
  'bitcoin': Bitcoin,
  'ethereum': Blocks,
  'nft': Blocks,
  'web3': Blocks,
  'defi': Wallet,
  'smart contract': Code2,
  
  // Business & ERP
  'erp': Building,
  'enterprise': Building,
  'crm': Users,
  'customer': Users,
  'sales': TrendingUp,
  'finance': Wallet,
  'financial': Wallet,
  'accounting': Calculator,
  'hr': Users,
  'human resources': Users,
  'payroll': DollarSign,
  'inventory': Package,
  'supply': Truck,
  'logistics': Truck,
  
  // Career & Resume
  'career': Briefcase,
  'resume': FileText,
  'cv': FileText,
  'portfolio': FolderOpen,
  'cover letter': Mail,
  'cover-letter': Mail,
  'interview': MessageCircle,
  'job': Briefcase,
  'employment': Briefcase,
  'recruitment': Users,
  'hiring': Users,
  'linkedin': Linkedin,
  'networking': Users2,
  
  // Design & Creative
  'design': Palette,
  'graphic': Palette,
  'ui': PenTool,
  'ux': PenTool,
  'user interface': PenTool,
  'user experience': PenTool,
  'figma': Figma,
  'sketch': PenTool,
  'photoshop': Image,
  'illustrator': PenTool,
  'branding': Award,
  'logo': Star,
  'creative': Sparkles,
  'art': Palette,
  
  // Development
  'development': Code2,
  'coding': Code2,
  'programming': Code2,
  'software': Code2,
  'engineering': Code2,
  'frontend': Layout,
  'backend': Server,
  'full stack': Layers,
  'fullstack': Layers,
  'api': Terminal,
  'rest': Terminal,
  'graphql': Terminal,
  'testing': CheckCircle,
  'qa': CheckCircle,
  'debug': Bug,
  'git': Github,
  'version control': Gitlab,
  'ci/cd': Rocket,
  'deployment': Rocket,
  
  // Marketing & Social
  'marketing': Megaphone,
  'social media': Megaphone,
  'seo': TrendingUp,
  'sem': TrendingUp,
  'ppc': Target,
  'advertising': Megaphone,
  'email': Mail,
  'newsletter': MailOpen,
  'content': FileEdit,
  'blog': FileText,
  'influencer': Star,
  'campaign': Megaphone,
  
  // E-commerce
  'ecommerce': ShoppingCart,
  'e-commerce': ShoppingCart,
  'store': Store,
  'shop': ShoppingCart,
  'product': Package,
  'cart': ShoppingCart,
  'checkout': CreditCard,
  'payment': CreditCard,
  'pos': Calculator,
  
  // Education & Learning
  'education': GraduationCap,
  'learning': BookOpen,
  'course': BookOpen,
  'training': GraduationCap,
  'tutorial': Video,
  'workshop': Presentation,
  'certification': Award,
  'certificate': Award,
  'degree': GraduationCap,
  'school': GraduationCap,
  'university': GraduationCap,
  
  // Media & Entertainment
  'video': Video,
  'audio': Mic,
  'music': Music,
  'streaming': Play,
  'gaming': Gamepad2,
  'animation': Film,
  'film': Camera,
  'photography': Camera,
  'podcast': Mic,
  
  // Productivity & Tools
  'productivity': Zap,
  'tool': Wrench,
  'utility': Settings,
  'extension': Puzzle,
  'plugin': Puzzle,
  'integration': Link,
  'scheduling': Calendar,
  'task': CheckSquare,
  'project': Kanban,
  'management': Users,
  
  // Communication
  'communication': MessageSquare,
  'messaging': MessageSquare,
  'chat': MessageCircle,
  'voip': Phone,
  'call': Phone,
  'video call': Video,
  'meeting': Users,
  'collaboration': Users2,
  'team': Users2,
  
  // Location & Travel
  'location': MapPin,
  'map': Map,
  'gps': Navigation,
  'travel': Plane,
  'transport': Car,
  'delivery': Truck,
  'shipping': Truck,
  
  // Health & Medical
  'health': Stethoscope,
  'medical': Stethoscope,
  'fitness': Activity,
  'wellness': Heart,
  'doctor': Stethoscope,
  'hospital': Building2,
  'pharmacy': Pill,
  
  // Default fallback
  'default': Sparkles,
  'unknown': Sparkles,
  'general': Sparkles,
  'service': Sparkles,
};

/**
 * Find the best matching Lucide icon based on service name, category, or description
 * @param serviceName - The name of the service
 * @param category - The category of the service (optional)
 * @param description - The description of the service (optional)
 * @returns A Lucide icon component
 */
export function getServiceIcon(
  serviceName?: string,
  category?: string,
  description?: string
): LucideIcon {
  const searchTerms = [
    serviceName?.toLowerCase() || '',
    category?.toLowerCase() || '',
    description?.toLowerCase() || '',
  ].join(' ');

  // Try exact matches first
  for (const [key, icon] of Object.entries(iconMapping)) {
    if (searchTerms.includes(key)) {
      return icon;
    }
  }

  // Try partial matches
  for (const [key, icon] of Object.entries(iconMapping)) {
    if (searchTerms.includes(key.split(' ')[0])) {
      return icon;
    }
  }

  // Fallback to default
  return Sparkles;
}

/**
 * Get icon name for storage/display purposes
 * @param icon - The Lucide icon component
 * @returns The name of the icon
 */
export function getIconName(icon: LucideIcon): string {
  const iconMap = Object.entries(iconMapping).find(([_, value]) => value === icon);
  return iconMap?.[0] || 'sparkles';
}

/**
 * Get all available icon mappings (for admin reference)
 * @returns The icon mapping object
 */
export function getIconMappings(): IconMap {
  return iconMapping;
}
